#!/usr/bin/bash

if python3.11 -m pytest --cov-config=.coveragerc --cov-report term-missing --cov=main tests/; then
    git add .
    git commit -m "autocommit: passing all tests with >= 90% coverage"
fi
